In [2]:
import numpy as np
#np.random.seed(42)

In [3]:
feature_vector=2
sample=1000
x_data=np.random.rand(sample,feature_vector)
ones_array=np.ones(sample).reshape(sample,1)
x_final=np.append(ones_array,x_data,axis=1)
beta=np.random.rand(feature_vector+1,1)
noise=np.random.randn(sample,1)
y_data=np.dot(x_final,beta)
y_final=y_data+noise
print(x_final.shape)
print(y_final.shape)
print(beta.shape)
print(noise.shape)

(1000, 3)
(1000, 1)
(3, 1)
(1000, 1)


In [4]:
#feature_vector=2
#sample=1000
#from numpy import genfromtxt
#x_final=genfromtxt('x.csv', delimiter=',')
#y_final=genfromtxt('y.csv', delimiter=',')

In [5]:
new_beta=np.random.rand(feature_vector+1,1)   #randn ?
new_beta.shape

(3, 1)

In [6]:
for i in range(10000):
    
    y_hat=np.dot(x_final,new_beta)
    y_difference=y_final-y_hat
    y_equation=-2*(np.transpose(y_difference))
    derivative=np.dot(y_equation,x_final)/sample
    #print(derivative) 
    new_beta=(new_beta)-0.1*(derivative.T)
    y_square=np.square(y_difference)
    cost_value=np.sum(y_square)/sample
    #cost_array.append(cost_value)
print(cost_value)   
print(new_beta)
    

#if cost_array[i-1]-cost_array[i] <0.000001:
#    #print(cost_array[i-1],cost_array[i])
#    break
#x_final.shape    

0.8614011549711585
[[ 0.44624392]
 [-0.05310817]
 [ 0.59439348]]


In [7]:
from sklearn.linear_model import LinearRegression
regressor= LinearRegression()

regressor.fit(x_data,y_final)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
y_pred=regressor.predict(x_data)

In [9]:
regressor.coef_

array([[-0.05310817,  0.59439348]])

In [10]:
regressor.intercept_

array([0.44624392])

In [11]:
import sklearn
sklearn.metrics.mean_squared_error(y_final,y_pred)

0.8614011549711584

In [12]:
derivative

array([[ 2.55795385e-16, -3.19744231e-17, -4.94715380e-16]])